apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-2-db
  labels:
    type: db
    service: go-demo-2
    vendor: MongoLabs
spec:
  replicas: 1
  selector:
    matchLabels: &Labels
      type: db
      service: go-demo-2
  template:
    metadata:
      labels: *Labels
    spec:
      containers:
        - name: db
          image: mongo:3.3
          ports:
            - containerPort: 27017
              protocol: TCP

--- 

apiVersion: v1
kind: Service
metadata:
  name: go-demo-2-db
spec:
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
  selector:
    type: db
    service: go-demo-2

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-2-api
  labels:
    type: api
    service: go-demo-2
    language: go
spec:
  replicas: 3
  selector:
    matchLabels:
      type: api
      service: go-demo-2
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        type: api
        service: go-demo-2
        db: mongo
        language: go
    spec:
      containers:
        - name: api
          image: vfarcic/go-demo-2
          env:
            - name: DB
              value: go-demo-2-db
          readinessProbe:
            httpGet:
              path: /demo/hello
              port: 8080
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /demo/hello
              port: 8080

--- 

apiVersion: v1
kind: Service
metadata:
  name: go-demo-2-api
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    type: api
    service: go-demo-2

#kubectl scale deployment go-demo-2-api --replicas=8 --record
