apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-demo-2                     # replicaSet name
spec:
  replicas: 2
  selector:                           # replicaSet selector matching pod labels
    matchLabels:
      type: backend
      service: go-demo-2
  template:                           # pod definition
    metadata:                         # dinamic pod name
      labels:                         # label selector
        type: backend
        service: go-demo-2
        db: mongo
        language: go
    spec:
      containers:
        - name: db
          image: mongo:3.3
        - name: api
          image: vfarcic/go-demo-2
          env:
            - name: DB
              value: localhost
          livenessProbe:
            httpGet:
              path: /demo/hello
              port: 8080
