---
- name: Prepare
  hosts: all
  become: true
  roles:
    - role: apt
      apt_manage_sources_list: true
      apt_remove_purge: true
      apt_keys:
        - keyserver: keyserver.ubuntu.com
          id: 7EA0A9C3F273FCD8
      apt_repositories:
        - repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      apt_gpg_keys:
        - url: https://download.docker.com/linux/ubuntu/gpg
          keyring: /etc/apt/keyrings/docker.gpg
      apt_install:
        - name: mc
        - name: ncdu