apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    type: db
    vendor: MongoLabs
spec:
  containers:
    - name: db
      image: mongo:3.3
      command: ["mongod"]
      args: ["--rest", "--httpinterface"]

# kubectl exec -it pod/db -- bash
# echo 'db.stats()' | mongo localhost:27017/test
