apiVersion: v1
kind: Pod
metadata:
  name: go-demo-2
  labels:
    type: stack
spec:
  containers:
    - name: db
      image: mongo:latest
    - name: api
      image: vfarcic/go-demo-2
      livenessProbe:
        httpGet:
          path: /this/path/does/not/exist
          port: 8080
        initialDelaySeconds: 5  # wait for 5 seconds after startup
        timeoutSeconds: 2       # Default to 1
        periodSeconds: 5        # Default to 10
        failureThreshold: 1     # Default to 3
      env:
        - name: DB
          value: localhost
